version: '3'

services:
  db:
    image: postgres:14.3
    ports:
      - ${PORT_DB}:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_DB: ${NAME_DB}
    container_name: teslodb
    volumes:      
      - ./postgres:/var/lib/postgresql/data